# Generated by Django 5.0 on 2023-12-17 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(max_length=255)),
                ('corporate_name', models.CharField(max_length=255)),
                ('corporate_type_id', models.CharField(max_length=255)),
                ('pcc_code', models.IntegerField()),
                ('office_number', models.CharField(max_length=20)),
                ('customer_category_id', models.IntegerField()),
                ('time_zone_key', models.CharField(max_length=255)),
                ('corporate_address', models.TextField()),
                ('pos_code', models.CharField(max_length=10)),
                ('corporate_status', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm_code', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email_id', models.EmailField(max_length=254)),
                ('user_address', models.TextField()),
                ('country_code', models.CharField(max_length=2)),
                ('city_id', models.CharField(max_length=255)),
                ('user_zip_code', models.IntegerField()),
                ('phone_number', models.CharField(max_length=20)),
                ('approved_status', models.CharField(max_length=1)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThejsonCruderApp.account')),
            ],
        ),
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=255)),
                ('is_direct', models.BooleanField()),
                ('active_status', models.CharField(max_length=1)),
                ('corporate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThejsonCruderApp.account')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ThejsonCruderApp.contact')),
            ],
        ),
    ]
