# Generated by Django 5.0 on 2023-12-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThejsonCruderApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='pcc_code',
            field=models.IntegerField(default=0),
        ),
    ]
