# Generated by Django 5.0 on 2023-12-17 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThejsonCruderApp', '0002_alter_account_pcc_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_category_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_zip_code',
            field=models.IntegerField(default=0),
        ),
    ]
