# Generated by Django 5.0 on 2023-12-17 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThejsonCruderApp', '0003_alter_account_customer_category_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='corporate_type_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='customer_category_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='account',
            name='time_zone_key',
            field=models.CharField(max_length=50),
        ),
    ]
