# Generated by Django 5.0 on 2023-12-17 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThejsonCruderApp', '0004_alter_account_corporate_type_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer_category_id',
            field=models.IntegerField(default=0),
        ),
    ]
