# Generated by Django 5.0 on 2023-12-17 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThejsonCruderApp', '0005_alter_account_customer_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relation',
            old_name='corporate_id',
            new_name='corporate',
        ),
        migrations.RenameField(
            model_name='relation',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='account',
            name='customer_category_id',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='account',
            name='pcc_code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='approved_status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email_id',
            field=models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator()]),
        ),
        migrations.AlterField(
            model_name='contact',
            name='user_zip_code',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='relation',
            name='active_status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
