# Generated by Django 5.0 on 2023-12-17 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThejsonCruderApp', '0006_rename_corporate_id_relation_corporate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='account',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='corporate',
        ),
        migrations.RemoveField(
            model_name='relation',
            name='user',
        ),
        migrations.AddField(
            model_name='relation',
            name='corporate_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='relation',
            name='user_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='corporate_status',
            field=models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=1),
        ),
    ]
