# Generated by Django 5.0 on 2023-12-17 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThejsonCruderApp', '0007_remove_contact_account_remove_relation_corporate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='account_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
