# Generated by Django 5.0 on 2023-12-17 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThejsonCruderApp', '0008_contact_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='confirm_code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
